### ISSUE TITLE
Now Make the Pass Do Something Mildly Interesting

### ISSUE THREAD

**Issue by nezzariyasser** [sampsyo/llvm-pass-skeleton#5]
Hello, 

I would like to thank you very much for your code, I'm new to LLVM so this might seem like a silly question but each time I try to build your code it gives me this error:
"Skeleton.cpp:30:32: error: ‘class llvm::BinaryOperator’ has no member named ‘uses’
             for (auto &U : op->uses()) {"
I'm using llvm-3.4 could please let me know how to fix this error.

Best regards.

YN

**Comment by sampsyo** [comment]
Hi! Can you please try with LLVM 3.6? It looks like `Value::uses` was added in the middle of 2014: https://github.com/llvm-mirror/llvm/commit/36b699f2b139a30a2dfa4448223d6985b55daa8a

And LLVM 3.4 was released earlier in that year.

**Comment by nezzariyasser** [comment]
Thank you very much, it works with LLVM 3.6

**Comment by sampsyo** [comment]
Great!
