### ISSUE TITLE
Error while making rtlib example

### ISSUE THREAD

**Issue by youngmaia5** [sampsyo/llvm-pass-skeleton#19]
Hi,

I ran into an error when I tried to run "make" on the rtlib example. The output is below. Do you have any suggestions on how to fix this error?

```
Scanning dependencies of target SkeletonPass
[ 50%] Building CXX object skeleton/CMakeFiles/SkeletonPass.dir/Skeleton.cpp.o
/llvm-pass-skeleton/skeleton/Skeleton.cpp: In member function ‘virtual bool {anonymous}::SkeletonPass::runOnFunction(llvm::Function&)’:
/llvm-pass-skeleton/skeleton/Skeleton.cpp:23:84: error: cannot convert ‘llvm::FunctionCallee’ to ‘llvm::Constant*’ in initialization
      Constant *logFunc = F.getParent()->getOrInsertFunction("logop", logFuncType);
                                                                                 ^
skeleton/CMakeFiles/SkeletonPass.dir/build.make:62: recipe for target 'skeleton/CMakeFiles/SkeletonPass.dir/Skeleton.cpp.o' failed
make[2]: *** [skeleton/CMakeFiles/SkeletonPass.dir/Skeleton.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'skeleton/CMakeFiles/SkeletonPass.dir/all' failed
make[1]: *** [skeleton/CMakeFiles/SkeletonPass.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Thank you!

**Comment by sampsyo** [comment]
Hello! As the README says, this repository currently targets LLVM 3.8. Which version are you trying to use?

**Comment by youngmaia5** [comment]
I'm using LLVM 8.0. However, I also followed another tutorial by Mike Shah (Northeastern+MIT LLVM Seminar - Introduction to LLVM) that works with LLVM 8.0, and I get the same error using his code. So, I'm thinking it does not have to do with the LLVM version. What do you think?

**Comment by sampsyo** [comment]
I'm not sure about that other tutorial, but I'm nearly certain that this error with this code is version-related. In 3.8, `getOrInsertFunction` returned a `Function*`. Now, it returns a `FunctionCallee`. You can either try with 3.8 or—if you're feeling generous!—help update the code for the new API changes since then.

**Comment by youngmaia5** [comment]
OK, that makes sense. Thank you!

**Comment by alisemi** [comment]
I came here following the Mike Shah's seminar, and I am using LLVM version 11.0. Here is my solution for the problem:
Change the line
Constant* hook = M.getOrInsertFunction(InstrumentingFunctionName, funcTy);
to
Value* hook = M.getOrInsertFunction(InstrumentingFunctionName, funcTy).getCallee();

and add #include "llvm/IR/Value.h" . Here is the explanation, the FunctionCallee class has a *Value attribute and Value class is a super class of Constant. In the new version of LLVM, the CallInst::Create also takes *Value as parameter rather than *Constant. Alternatively, passing the FunctionCallee as an argument to CallInst::Create might also work.

**Comment by gururaj-s** [comment]
To build on the previous answer - the exact changes needed in the Skeleton.cpp code to make it work with LLVM-10 were the following:

Change  line-23 from Constant *logFunc = F.getParent()->getOrInsertFunction("logop", logFuncType);
to :  FunctionCallee logFunc = F.getParent()->getOrInsertFunction("logop", logFuncType);

Change line-34 from  builder.CreateCall(logFunc, args);
to :  builder.CreateCall(logFuncType,logFunc.getCallee(), args);
